config/routes.rb
Tdn::Application.routes.draw do
  resources :articles
  resources :relationships
  resources :tiles
  resources :buildings
  resources :building_types

  root to: 'application#home'

  post   '/sign_in',  to: 'sessions#create',  as: 'sign_in'
  delete '/sign_out', to: 'sessions#destroy', as: 'sign_out'
  get    '/sign_up',  to: 'users#new',        as: 'sign_up'

  post   '/users',    to: 'users#create'

  get '/game', to: 'tiles#index'

  get '/cities', to: 'cities#index'

  resources :technologies
  resources :discoveries

end

app/models/article.rb
class Article < ActiveRecord::Base
  attr_accessible :title, :content

  validates_presence_of :title, :content
  validates_uniqueness_of :title
end

app/models/building.rb
class Building < ActiveRecord::Base
  belongs_to :building_type
  belongs_to :city
  has_many :tiles
  attr_accessible :city_id, :building_type_id
end

app/models/building_type.rb
class BuildingType < ActiveRecord::Base
  attr_accessible :name, :description, :width, :height, :land_type_required
  has_many :buildings
end

app/models/city.rb
class City < ActiveRecord::Base
  belongs_to :user
  has_many :tiles
  has_many :buildings

  attr_accessible :name, :labroer, :city, :deben



  def generate_name(user)
  	"#{user.name.capitalize}'s city"
  end

  def to_s
  	"#{name}"
  end

  def generate_map
    fields = ['f', 'h', 'w', 'p', 'a']
    City.transaction do
      200.times do |x|
        50.times do |y|
          self.tiles.create(x: x, y: y, land_type: fields.sample)
        end
      end
    end
  end
end

app/models/discovery.rb
class Discovery < ActiveRecord::Base
  belongs_to :user
  belongs_to :technology

  attr_accessible :technology_id, :user_id

  validates_uniqueness_of :technology_id, scope: :user_id
end

app/models/relationship.rb
class Relationship < ActiveRecord::Base
  belongs_to :parent, class_name: "Technology"
  belongs_to :child, class_name: "Technology"

  attr_accessible :child_id, :parent_id

  accepts_nested_attributes_for :parent
  accepts_nested_attributes_for :child
end

app/models/technology.rb
class Technology < ActiveRecord::Base
  has_many :discoveries
  has_many :users, through: :discoveries

  has_many :ancestors, class_name: "Relationship", foreign_key: "child_id", dependent: :destroy
  has_many :parents, through: :ancestors, source: :parent
  has_many :descendants, class_name: "Relationship", foreign_key: "parent_id", dependent: :destroy
  has_many :children, through: :descendants, source: :child

  validates :name, uniqueness: true
  attr_accessible :name, :depth
  # Technology.select("sum(depth)/depth as max_depth_sibling ").group(:depth).order("max_depth_sibling DESC").first
end

app/models/tile.rb
class Tile < ActiveRecord::Base
  belongs_to :city
  belongs_to :building

  attr_accessible :land_type, :x, :y, :city

  def self.range(x_min, y_min, x_max, y_max)
    self.where('x >= ? AND x <= ? AND y >= ? AND y <= ?', x_min, x_max, y_min, y_max)
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password

  has_many :discoveries
  has_many :technologies, through: :discoveries
  has_one :city

  attr_accessible :name, :email, :password, :password_confirmation

  validates :name, length: 2..20,
                   format: /^[a-z-]+$/i,
                   uniqueness: true,
                   presence: true

  validates :email, format: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i,
                    presence: true,
                    uniqueness: true

  validates_presence_of :password, :password_confirmation, on: :create

  def self.generate_token
    existing_tokens = User.select :token

    begin
      token = SecureRandom.hex
    end while existing_tokens.include?(token)

    token
  end

  def assign_city
    User.transaction do
      city = City.new
      city.name = city.generate_name(self)
      city.user = self
      city.deben = 1000
      city.save!

      city.generate_map
    end
  end

  def to_s
    "#{name}"
  end

  def available_building_types
    BuildingType.all
  end
end

app/controllers/game_controller.rb
class GameController < ApplicationController
  layout 'game'

end

app/controllers/tiles_controller.rb
class TilesController < GameController

  def index
    @city = current_user.city
    if params.has_key?(:x) && params.has_key?(:y)
      x_start = params[:x].to_i
      y_start = params[:y].to_i
    else
      x_start = 1
      y_start = 1
    end

    max_x = @city.tiles.maximum("x")
    max_y = @city.tiles.maximum("y")

    width  = 35
    @width = width
    height = 15
    #@tiles = @city.tiles.where('x >= ?', x_start).where('x < ?', x_start+width).where('y >= ?', y_start ).where('y < ?', y_start+height).order('y ASC').order('x ASC').includes(:building => :building_type)
    @tiles = @city.tiles.range(x_start, y_start, x_start+width-1, y_start+height-1).order('y ASC').order('x ASC').includes(:building => :building_type)

    @current_x = x_start
    @current_y = y_start

    @next_x = x_start+1
    @next_y = y_start+1
    @prev_x = x_start-1
    @prev_y = y_start-1

    if @current_x == 1
      @prev_x = @current_x
    end
    if @current_y == 1
      @prev_y = @current_y
    end
    if @next_x > max_x
      @next_x = @current_x
    end
    if @next_y > max_y
      @next_y = @current_y
    end

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/helpers/discoveries_helper.rb
module DiscoveriesHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/technologies_helper.rb
module TechnologiesHelper
end

app/helpers/tiles_helper.rb
module TilesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.haml
!!!
%html{:lang => "en"}
  %head
    %meta{:charset => "utf-8"}/
    %meta{:content => "width=device-width, initial-scale=1.0", :name => "viewport"}/
    %title= content_for?(:title) ? yield(:title) : "Tdn"
    = csrf_meta_tags
    / Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
    = stylesheet_link_tag "application", :media => "all"
    %link{:href => "images/favicon.ico", :rel => "shortcut icon"}/
    %link{:href => "images/apple-touch-icon.png", :rel => "apple-touch-icon"}/
    %link{:href => "images/apple-touch-icon-72x72.png", :rel => "apple-touch-icon", :sizes => "72x72"}/
    %link{:href => "images/apple-touch-icon-114x114.png", :rel => "apple-touch-icon", :sizes => "114x114"}/
  %body
    .navbar.navbar-fixed-top
      .navbar-inner
        .container
          %a.btn.btn-navbar{"data-target" => ".nav-collapse", "data-toggle" => "collapse"}
            %span.icon-bar
            %span.icon-bar
            %span.icon-bar
          %a.brand{:href => "/"} Terres du Nil
          .container.nav-collapse
            %ul.nav
              %li= link_to "Home", root_url
              - if current_user
                %li= link_to "Game", "/game"
            -if current_user
              %ul.nav.pull-right
                %li
                  = link_to sign_out_path, method: 'delete' do
                    %i.icon-off
                    Logout
          / /.nav-collapse
    .container
      .content
        .row
          .span9
            = yield
          .span3
            - if !current_user
              .well.sidebar-nav
                %h3 Sign In
                = render partial: 'users/sign_in_form', user: @user
                = link_to "Create an account", sign_up_path
            .well.sidebar-nav
              %h3 About us
              %p Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed iaculis libero quis massa viverra id semper nulla consequat. Fusce sagittis, neque quis suscipit suscipit, massa metus ultrices orci, ut molestie libero felis et odio. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam fermentum purus a mauris mollis ut lacinia enim pulvinar. Vivamus non dolor id metus accumsan vehicula. Duis vestibulum, turpis in facilisis convallis, sapien mauris lobortis augue, vel feugiat magna elit sed sapien.
            / /.well
          / /span
        / /row
      / /content
      %footer
        %p &copy; Terres du Nil 2012
    / /container
    /
      Javascripts
      \==================================================
    / Placed at the end of the document so the pages load faster
    = javascript_include_tag "application"

app/views/layouts/game.html.haml
!!!
%html{:lang => "en"}
  %head
    %meta{:charset => "utf-8"}/
    %meta{:content => "width=device-width, initial-scale=1.0", :name => "viewport"}/
    %title= content_for?(:title) ? yield(:title) : "Tdn"
    = csrf_meta_tags
    / Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
    = stylesheet_link_tag "application", :media => "all"
    %link{:href => "images/favicon.ico", :rel => "shortcut icon"}/
    %link{:href => "images/apple-touch-icon.png", :rel => "apple-touch-icon"}/
    %link{:href => "images/apple-touch-icon-72x72.png", :rel => "apple-touch-icon", :sizes => "72x72"}/
    %link{:href => "images/apple-touch-icon-114x114.png", :rel => "apple-touch-icon", :sizes => "114x114"}/
  %body
    .navbar.navbar-fixed-top
      .navbar-inner
        .container
          %a.btn.btn-navbar{"data-target" => ".nav-collapse", "data-toggle" => "collapse"}
            %span.icon-bar
            %span.icon-bar
            %span.icon-bar
          %a.brand{:href => "/"} Terres du Nil
          .container.nav-collapse
            %ul.nav
              %li= link_to current_user.city, game_path
              %li= link_to 'Cities list', cities_path
              %li= link_to 'Map', tiles_path
              %li.dropdown
                = link_to "#", data: {toggle: "dropdown"}, class: "dropdown-toggle" do
                  Technologies
                  %b.caret
                %ul.dropdown-menu
                  %li= link_to "Discovered", discoveries_path
                  %li= link_to "All of them", technologies_path
              %li
                = link_to "#" do
                  %i.icon-star
                  = "#{current_user.city.deben} debens"
              %li
                = link_to "#" do
                  %i.icon-user
                  = current_user.city.laborer
              %li
                = link_to "#" do
                  %i.icon-thumbs-up
                  = current_user.city.happiness
            %ul.nav.pull-right
              %li
                = link_to sign_out_path, method: 'delete' do
                  %i.icon-off
                  Logout
          / /.nav-collapse
    .container
      .content
        .row
          - [:notice,:error].each do |type|
            = content_tag(:div, flash[type], :class => type) if flash[type]
          = yield
        / /row
      / /content
    .navbar.navbar-fixed-bottom
      .navbar-inner
        .container
          .container.nav-collapse
            %ul.nav
              %li.dropdown
                = link_to building_types_path, data: {remote: true, target: "#"}, class: "dropdown-toggle" do
                  %i.icon-home
                  Buildings
                  %b.caret
                %ul.dropdown-menu{id: "buildings"}
                  %li Loading...
          / /.nav-collapse
    / /container
    /
      Javascripts
      \==================================================
    / Placed at the end of the document so the pages load faster
    = javascript_include_tag "application"